- // MIR for `test` before RangeAnalysisPass
+ // MIR for `test` after RangeAnalysisPass
  
  fn test(_1: u8, _2: u8) -> () {
      debug x => _1;
      debug y => _2;
      let mut _0: ();
      let _3: ();
      let mut _4: bool;
      let mut _5: u8;
      let _6: ();
      let mut _7: bool;
      let mut _8: u8;
      let mut _9: !;
      let _10: ();
      let mut _11: bool;
      let mut _12: u8;
      let mut _13: !;
      let _14: u8;
      let mut _15: u8;
      let mut _16: u8;
      let mut _18: u8;
      let mut _19: u8;
      let mut _21: u8;
      let mut _22: u8;
      let mut _23: bool;
      let mut _24: u8;
      let mut _25: bool;
      let mut _26: u8;
      let _27: ();
      let mut _28: bool;
      let mut _29: u8;
      let mut _30: bool;
      let mut _31: u8;
      let mut _32: !;
      let _33: ();
      let mut _34: bool;
      let mut _35: u8;
      let mut _36: bool;
      let mut _37: u8;
      let mut _38: !;
      let _39: ();
      let mut _40: bool;
      let mut _41: u8;
      let mut _42: bool;
      let mut _43: u8;
      let mut _44: !;
      scope 1 {
          debug and_result => _14;
          let _17: u8;
          scope 2 {
              debug or_result => _17;
              let _20: u8;
              scope 3 {
                  debug xor_result => _20;
              }
          }
      }
  
      bb0: {
          StorageLive(_3);
          StorageLive(_4);
          StorageLive(_5);
          _5 = copy _1;
          _4 = Le(move _5, const 10_u8);
          switchInt(move _4) -> [0: bb4, otherwise: bb1];
      }
  
      bb1: {
          StorageDead(_5);
          StorageLive(_6);
          StorageLive(_7);
          StorageLive(_8);
          _8 = copy _1;
-         _7 = Le(move _8, const 10_u8);
-         switchInt(move _7) -> [0: bb3, otherwise: bb2];
+         _7 = const true;
+         nop;
+         goto -> bb2;
      }
  
      bb2: {
          StorageDead(_8);
          _6 = const ();
          StorageDead(_7);
          StorageDead(_6);
          _3 = const ();
          goto -> bb7;
      }
  
      bb3: {
          StorageDead(_8);
          StorageLive(_9);
          _9 = core::panicking::panic(const "assertion failed: x <= 10") -> unwind continue;
      }
  
      bb4: {
          StorageDead(_5);
          StorageLive(_10);
          StorageLive(_11);
          StorageLive(_12);
          _12 = copy _1;
          _11 = Lt(move _12, const 100_u8);
          switchInt(move _11) -> [0: bb6, otherwise: bb5];
      }
  
      bb5: {
          StorageDead(_12);
          _10 = const ();
          StorageDead(_11);
          StorageDead(_10);
          _3 = const ();
          goto -> bb7;
      }
  
      bb6: {
          StorageDead(_12);
          StorageLive(_13);
          _13 = core::panicking::panic(const "assertion failed: x < 100") -> unwind continue;
      }
  
      bb7: {
          StorageDead(_4);
          StorageDead(_3);
          StorageLive(_14);
          StorageLive(_15);
          _15 = copy _1;
          StorageLive(_16);
          _16 = copy _2;
          _14 = BitAnd(move _15, move _16);
          StorageDead(_16);
          StorageDead(_15);
          StorageLive(_17);
          StorageLive(_18);
          _18 = copy _1;
          StorageLive(_19);
          _19 = copy _2;
          _17 = BitOr(move _18, move _19);
          StorageDead(_19);
          StorageDead(_18);
          StorageLive(_20);
          StorageLive(_21);
          _21 = copy _1;
          StorageLive(_22);
          _22 = copy _2;
          _20 = BitXor(move _21, move _22);
          StorageDead(_22);
          StorageDead(_21);
          StorageLive(_23);
          StorageLive(_24);
          _24 = copy _1;
          _23 = Le(move _24, const 10_u8);
          switchInt(move _23) -> [0: bb26, otherwise: bb8];
      }
  
      bb8: {
          StorageDead(_24);
          StorageLive(_25);
          StorageLive(_26);
          _26 = copy _2;
          _25 = Le(move _26, const 10_u8);
          switchInt(move _25) -> [0: bb25, otherwise: bb9];
      }
  
      bb9: {
          StorageDead(_26);
          StorageLive(_27);
          StorageLive(_28);
          StorageLive(_29);
          _29 = copy _14;
-         _28 = Ge(move _29, const 0_u8);
-         switchInt(move _28) -> [0: bb13, otherwise: bb10];
+         _28 = const true;
+         nop;
+         goto -> bb10;
      }
  
      bb10: {
          StorageDead(_29);
          StorageLive(_30);
          StorageLive(_31);
          _31 = copy _14;
          _30 = Le(move _31, const 10_u8);
          switchInt(move _30) -> [0: bb12, otherwise: bb11];
      }
  
      bb11: {
          StorageDead(_31);
          _27 = const ();
          StorageDead(_30);
          StorageDead(_28);
          StorageDead(_27);
          StorageLive(_33);
          StorageLive(_34);
          StorageLive(_35);
          _35 = copy _17;
-         _34 = Ge(move _35, const 0_u8);
-         switchInt(move _34) -> [0: bb16, otherwise: bb15];
+         _34 = const true;
+         nop;
+         goto -> bb15;
      }
  
      bb12: {
          StorageDead(_31);
          goto -> bb14;
      }
  
      bb13: {
          StorageDead(_29);
          goto -> bb14;
      }
  
      bb14: {
          StorageLive(_32);
          _32 = core::panicking::panic(const "assertion failed: and_result >= 0 && and_result <= 10") -> unwind continue;
      }
  
      bb15: {
          StorageDead(_35);
          StorageLive(_36);
          StorageLive(_37);
          _37 = copy _17;
          _36 = Le(move _37, const 10_u8);
          switchInt(move _36) -> [0: bb18, otherwise: bb17];
      }
  
      bb16: {
          StorageDead(_35);
          goto -> bb19;
      }
  
      bb17: {
          StorageDead(_37);
          _33 = const ();
          StorageDead(_36);
          StorageDead(_34);
          StorageDead(_33);
          StorageLive(_39);
          StorageLive(_40);
          StorageLive(_41);
          _41 = copy _20;
-         _40 = Ge(move _41, const 0_u8);
-         switchInt(move _40) -> [0: bb21, otherwise: bb20];
+         _40 = const true;
+         nop;
+         goto -> bb20;
      }
  
      bb18: {
          StorageDead(_37);
          goto -> bb19;
      }
  
      bb19: {
          StorageLive(_38);
          _38 = core::panicking::panic(const "assertion failed: or_result >= 0 && or_result <= 10") -> unwind continue;
      }
  
      bb20: {
          StorageDead(_41);
          StorageLive(_42);
          StorageLive(_43);
          _43 = copy _20;
          _42 = Le(move _43, const 10_u8);
          switchInt(move _42) -> [0: bb23, otherwise: bb22];
      }
  
      bb21: {
          StorageDead(_41);
          goto -> bb24;
      }
  
      bb22: {
          StorageDead(_43);
          _39 = const ();
          StorageDead(_42);
          StorageDead(_40);
          StorageDead(_39);
          _0 = const ();
          goto -> bb28;
      }
  
      bb23: {
          StorageDead(_43);
          goto -> bb24;
      }
  
      bb24: {
          StorageLive(_44);
          _44 = core::panicking::panic(const "assertion failed: xor_result >= 0 && xor_result <= 10") -> unwind continue;
      }
  
      bb25: {
          StorageDead(_26);
          goto -> bb27;
      }
  
      bb26: {
          StorageDead(_24);
          goto -> bb27;
      }
  
      bb27: {
          _0 = const ();
          goto -> bb28;
      }
  
      bb28: {
          StorageDead(_25);
          StorageDead(_23);
          StorageDead(_20);
          StorageDead(_17);
          StorageDead(_14);
          return;
      }
  }
  
  ALLOC0 (size: 53, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 6f 72 5f 72 65 73 75 6c 74 20 3e 3d 20 │ : xor_result >= 
      0x20 │ 30 20 26 26 20 78 6f 72 5f 72 65 73 75 6c 74 20 │ 0 && xor_result 
      0x30 │ 3c 3d 20 31 30                                  │ <= 10
  }
  
  ALLOC1 (size: 51, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 6f 72 5f 72 65 73 75 6c 74 20 3e 3d 20 30 │ : or_result >= 0
      0x20 │ 20 26 26 20 6f 72 5f 72 65 73 75 6c 74 20 3c 3d │  && or_result <=
      0x30 │ 20 31 30                                        │  10
  }
  
  ALLOC2 (size: 53, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 61 6e 64 5f 72 65 73 75 6c 74 20 3e 3d 20 │ : and_result >= 
      0x20 │ 30 20 26 26 20 61 6e 64 5f 72 65 73 75 6c 74 20 │ 0 && and_result 
      0x30 │ 3c 3d 20 31 30                                  │ <= 10
  }
  
  ALLOC3 (size: 25, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3c 20 31 30 30                      │ : x < 100
  }
  
  ALLOC4 (size: 25, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3c 3d 20 31 30                      │ : x <= 10
  }
  
