- // MIR for `test` before RangeAnalysisPass
+ // MIR for `test` after RangeAnalysisPass
  
  fn test() -> bool {
      let mut _0: bool;
      let mut _1: !;
      let mut _2: bool;
      let _4: ();
      let mut _5: ();
      let mut _6: bool;
      let mut _7: i32;
      let mut _8: i32;
      let mut _9: i32;
      let _12: ();
      let mut _13: bool;
      let mut _14: i32;
      let mut _15: i32;
      let mut _16: !;
      let _17: ();
      let mut _18: !;
      let mut _19: i32;
      let mut _20: i32;
      let mut _21: i32;
      let mut _22: i32;
      let mut _23: !;
      let _24: ();
      let mut _25: !;
      let mut _26: i32;
      scope 1 {
          debug cond => _2;
          let mut _3: i32;
          scope 2 {
              debug k => _3;
              let mut _10: i32;
              scope 3 {
                  debug i => _10;
                  let mut _11: i32;
                  scope 4 {
                      debug j => _11;
                  }
              }
          }
      }
  
      bb0: {
          StorageLive(_2);
          _2 = const true;
          StorageLive(_3);
          _3 = const 0_i32;
          StorageLive(_4);
          goto -> bb1;
      }
  
      bb1: {
          StorageLive(_6);
          StorageLive(_7);
          _7 = copy _3;
-         _6 = Lt(move _7, const 100_i32);
-         switchInt(move _6) -> [0: bb6, otherwise: bb2];
+         _6 = const true;
+         nop;
+         goto -> bb2;
      }
  
      bb2: {
          StorageDead(_7);
          StorageLive(_8);
          _8 = copy _3;
-         _2 = Ge(move _8, const 0_i32);
+         _2 = const true;
+         nop;
          StorageDead(_8);
          StorageLive(_9);
          _9 = copy _3;
          _2 = Le(move _9, const 99_i32);
          StorageDead(_9);
          StorageLive(_10);
          _10 = const 0_i32;
          StorageLive(_11);
          _11 = copy _3;
          StorageLive(_12);
          goto -> bb3;
      }
  
      bb3: {
          StorageLive(_13);
          StorageLive(_14);
          _14 = copy _10;
          StorageLive(_15);
          _15 = copy _11;
          _13 = Lt(move _14, move _15);
          switchInt(move _13) -> [0: bb5, otherwise: bb4];
      }
  
      bb4: {
          StorageDead(_15);
          StorageDead(_14);
          _10 = Add(copy _10, const 1_i32);
          _11 = Sub(copy _11, const 1_i32);
          _5 = const ();
          StorageDead(_13);
          goto -> bb3;
      }
  
      bb5: {
          StorageDead(_15);
          StorageDead(_14);
          StorageLive(_17);
          _12 = const ();
          StorageDead(_17);
          StorageDead(_13);
          StorageDead(_12);
          _3 = Add(copy _3, const 1_i32);
          StorageLive(_19);
          _19 = copy _10;
          _2 = Ge(move _19, const 0_i32);
          StorageDead(_19);
          StorageLive(_20);
          _20 = copy _11;
          _2 = Ge(move _20, const 0_i32);
          StorageDead(_20);
          StorageLive(_21);
          _21 = copy _10;
          _2 = Le(move _21, const 99_i32);
          StorageDead(_21);
          StorageLive(_22);
          _22 = copy _11;
          _2 = Le(move _22, const 99_i32);
          StorageDead(_22);
          _5 = const ();
          StorageDead(_11);
          StorageDead(_10);
          StorageDead(_6);
          goto -> bb1;
      }
  
      bb6: {
          StorageDead(_7);
          StorageLive(_24);
          _4 = const ();
          StorageDead(_24);
          StorageDead(_6);
          StorageDead(_4);
          StorageLive(_26);
          _26 = copy _3;
-         _2 = Ge(move _26, const 100_i32);
+         _2 = const false;
+         nop;
          StorageDead(_26);
          _0 = copy _2;
          StorageDead(_3);
          StorageDead(_2);
          return;
      }
  }
  
