- // MIR for `test` before RangeAnalysisPass
+ // MIR for `test` after RangeAnalysisPass
  
  fn test(_1: u8, _2: bool, _3: bool) -> () {
      debug x => _1;
      debug y => _2;
      debug z => _3;
      let mut _0: ();
      let _4: ();
      let mut _5: bool;
      let mut _6: u8;
      let _7: ();
      let mut _8: bool;
      let mut _9: u8;
      let mut _10: !;
      let _11: ();
      let mut _12: bool;
      let _13: ();
      let mut _14: bool;
      let mut _15: u8;
      let mut _16: bool;
      let mut _17: !;
      let _18: bool;
      let _19: ();
      let mut _20: bool;
      let _21: ();
      let mut _22: bool;
      let mut _23: u8;
      let mut _24: bool;
      let mut _25: !;
      let _26: ();
      let mut _27: bool;
      let mut _28: u8;
      let mut _29: bool;
      let mut _30: !;
      let mut _31: bool;
      let mut _32: u8;
      let mut _33: !;
      let mut _34: bool;
      let mut _35: u8;
      let mut _36: !;
      let mut _37: bool;
      let mut _38: u8;
      let mut _39: !;
      scope 1 {
          debug w => _18;
      }
  
      bb0: {
          StorageLive(_4);
          StorageLive(_5);
          StorageLive(_6);
          _6 = copy _1;
          _5 = Lt(move _6, const 5_u8);
          switchInt(move _5) -> [0: bb4, otherwise: bb1];
      }
  
      bb1: {
          StorageDead(_6);
          StorageLive(_7);
          StorageLive(_8);
          StorageLive(_9);
          _9 = copy _1;
-         _8 = Lt(move _9, const 5_u8);
-         switchInt(move _8) -> [0: bb3, otherwise: bb2];
+         _8 = const true;
+         nop;
+         goto -> bb2;
      }
  
      bb2: {
          StorageDead(_9);
          _7 = const ();
          StorageDead(_8);
          StorageDead(_7);
          _4 = const ();
          goto -> bb5;
      }
  
      bb3: {
          StorageDead(_9);
          StorageLive(_10);
          _10 = core::panicking::panic(const "assertion failed: x < 5") -> unwind unreachable;
      }
  
      bb4: {
          StorageDead(_6);
          _4 = const ();
          goto -> bb5;
      }
  
      bb5: {
          StorageDead(_5);
          StorageDead(_4);
          StorageLive(_11);
          StorageLive(_12);
          _12 = copy _2;
          switchInt(move _12) -> [0: bb6, otherwise: bb9];
      }
  
      bb6: {
          StorageLive(_13);
          StorageLive(_14);
          StorageLive(_15);
          StorageLive(_16);
          _16 = copy _2;
          _15 = move _16 as u8 (IntToInt);
          StorageDead(_16);
-         _14 = Eq(move _15, const 0_u8);
-         switchInt(move _14) -> [0: bb8, otherwise: bb7];
+         _14 = const true;
+         nop;
+         goto -> bb7;
      }
  
      bb7: {
          StorageDead(_15);
          _13 = const ();
          StorageDead(_14);
          StorageDead(_13);
          _11 = const ();
          goto -> bb10;
      }
  
      bb8: {
          StorageDead(_15);
          StorageLive(_17);
          _17 = core::panicking::panic(const "assertion failed: y as u8 == 0") -> unwind unreachable;
      }
  
      bb9: {
          _11 = const ();
          goto -> bb10;
      }
  
      bb10: {
          StorageDead(_12);
          StorageDead(_11);
          StorageLive(_18);
          _18 = copy _3;
          StorageLive(_19);
          StorageLive(_20);
          _20 = copy _18;
          switchInt(move _20) -> [0: bb11, otherwise: bb16];
      }
  
      bb11: {
          StorageLive(_21);
          StorageLive(_22);
          StorageLive(_23);
          StorageLive(_24);
          _24 = copy _3;
          _23 = move _24 as u8 (IntToInt);
          StorageDead(_24);
-         _22 = Eq(move _23, const 0_u8);
-         switchInt(move _22) -> [0: bb13, otherwise: bb12];
+         _22 = const true;
+         nop;
+         goto -> bb12;
      }
  
      bb12: {
          StorageDead(_23);
          _21 = const ();
          StorageDead(_22);
          StorageDead(_21);
          StorageLive(_26);
          StorageLive(_27);
          StorageLive(_28);
          StorageLive(_29);
          _29 = copy _18;
          _28 = move _29 as u8 (IntToInt);
          StorageDead(_29);
-         _27 = Eq(move _28, const 0_u8);
-         switchInt(move _27) -> [0: bb15, otherwise: bb14];
+         _27 = const true;
+         nop;
+         goto -> bb14;
      }
  
      bb13: {
          StorageDead(_23);
          StorageLive(_25);
          _25 = core::panicking::panic(const "assertion failed: z as u8 == 0") -> unwind unreachable;
      }
  
      bb14: {
          StorageDead(_28);
          _26 = const ();
          StorageDead(_27);
          StorageDead(_26);
          _19 = const ();
          goto -> bb17;
      }
  
      bb15: {
          StorageDead(_28);
          StorageLive(_30);
          _30 = core::panicking::panic(const "assertion failed: w as u8 == 0") -> unwind unreachable;
      }
  
      bb16: {
          _19 = const ();
          goto -> bb17;
      }
  
      bb17: {
          StorageDead(_20);
          StorageDead(_19);
          switchInt(copy _1) -> [1: bb21, 2: bb20, 10: bb19, otherwise: bb18];
      }
  
      bb18: {
          _0 = ();
          goto -> bb28;
      }
  
      bb19: {
          StorageLive(_37);
          StorageLive(_38);
          _38 = copy _1;
-         _37 = Eq(move _38, const 10_u8);
-         switchInt(move _37) -> [0: bb27, otherwise: bb26];
+         _37 = const true;
+         nop;
+         goto -> bb26;
      }
  
      bb20: {
          StorageLive(_34);
          StorageLive(_35);
          _35 = copy _1;
-         _34 = Eq(move _35, const 2_u8);
-         switchInt(move _34) -> [0: bb25, otherwise: bb24];
+         _34 = const true;
+         nop;
+         goto -> bb24;
      }
  
      bb21: {
          StorageLive(_31);
          StorageLive(_32);
          _32 = copy _1;
-         _31 = Eq(move _32, const 1_u8);
-         switchInt(move _31) -> [0: bb23, otherwise: bb22];
+         _31 = const true;
+         nop;
+         goto -> bb22;
      }
  
      bb22: {
          StorageDead(_32);
          _0 = const ();
          StorageDead(_31);
          goto -> bb28;
      }
  
      bb23: {
          StorageDead(_32);
          StorageLive(_33);
          _33 = core::panicking::panic(const "assertion failed: x == 1") -> unwind unreachable;
      }
  
      bb24: {
          StorageDead(_35);
          _0 = const ();
          StorageDead(_34);
          goto -> bb28;
      }
  
      bb25: {
          StorageDead(_35);
          StorageLive(_36);
          _36 = core::panicking::panic(const "assertion failed: x == 2") -> unwind unreachable;
      }
  
      bb26: {
          StorageDead(_38);
          _0 = const ();
          StorageDead(_37);
          goto -> bb28;
      }
  
      bb27: {
          StorageDead(_38);
          StorageLive(_39);
          _39 = core::panicking::panic(const "assertion failed: x == 10") -> unwind unreachable;
      }
  
      bb28: {
          StorageDead(_18);
          return;
      }
  }
  
  ALLOC0 (size: 25, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3d 3d 20 31 30                      │ : x == 10
  }
  
  ALLOC1 (size: 24, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3d 3d 20 32                         │ : x == 2
  }
  
  ALLOC2 (size: 24, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3d 3d 20 31                         │ : x == 1
  }
  
  ALLOC3 (size: 30, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 77 20 61 73 20 75 38 20 3d 3d 20 30       │ : w as u8 == 0
  }
  
  ALLOC4 (size: 30, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 7a 20 61 73 20 75 38 20 3d 3d 20 30       │ : z as u8 == 0
  }
  
  ALLOC5 (size: 30, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 79 20 61 73 20 75 38 20 3d 3d 20 30       │ : y as u8 == 0
  }
  
  ALLOC6 (size: 23, align: 1) {
      0x00 │ 61 73 73 65 72 74 69 6f 6e 20 66 61 69 6c 65 64 │ assertion failed
      0x10 │ 3a 20 78 20 3c 20 35                            │ : x < 5
  }
  
